services:
    nginx:
        image: nginx:1.27.1
        ports:
            - ${IP}:${NGINX_HTTP_PORT}:80
            - ${IP}:${NGINX_HTTPS_PORT}:443
        volumes:
            - ./data/nginx/default_${NGINX_PROTOCOL}.conf:/etc/nginx/conf.d/default.conf
            - ./data/html:/var/www/html
            - ./data/letsencrypt:/etc/letsencrypt
        links:
            - phpmyadmin:phpmyadmin
        depends_on:
            - phpmyadmin
    phpmyadmin:
        image: phpmyadmin:5.2.1
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ABSOLUTE_URI: ${NGINX_PROTOCOL}://${DOMAIN}:${NGINX_HTTP_PORT}/phpmyadmin
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        links:
            - mysql:mysql
        depends_on:
            - mysql
    mysql:
        build:
            context: ./data/mysql
            dockerfile: mysql.Dockerfile
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: no
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        volumes:
            - ./data/mysql/sql:/docker-entrypoint-initdb.d
            - mysql_volume:/var/lib/mysql
        ports:
            - ${IP}:${MYSQL_PORT}:3306

volumes:
    mysql_volume:
