services:
    nginx:
        image: nginx:1.27.1
        restart: no
        ports:
            - ${IP}:${NGINX_HTTP_PORT}:80
            - ${IP}:${NGINX_HTTPS_PORT}:443
        volumes:
            - ./data/nginx/${NGINX_CONF}:/etc/nginx/conf.d/default.conf
            - ./data/html:/var/www/html
            - ./data/letsencrypt:/etc/letsencrypt
            - ./data/flask/flask_app_to_deploy/static:/static
        links:
            - adminer:adminer
            - flask:flask
        depends_on:
            - adminer
            - flask
    adminer:
        image: ghcr.io/shyim/adminerevo:latest
        restart: no
        volumes:
            - ./data/adminer:/var/www/html/plugins-enabled
        links:
            - mysql:mysql
            - postgres:postgres
        depends_on:
            - mysql
            - postgres
    mysql:
        build:
            context: ./data/mysql
            dockerfile: mysql.Dockerfile
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: no
        environment:
            MYSQL_USER: "${FLASK_MYSQL_USER}"
            MYSQL_PASSWORD: "${FLASK_MYSQL_PASSWORD}"
            MYSQL_DATABASE: "${FLASK_MYSQL_DATABASE}"
            MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
        volumes:
            - ./data/mysql/sql:/docker-entrypoint-initdb.d
            - mysql_volume:/var/lib/mysql
        ports:
            - ${IP}:${MYSQL_PORT}:3306
    postgres:
        image: postgres:16.4
        restart: no
        environment:
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            PDDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ./data/postgres/sql:/docker-entrypoint-initdb.d
            - postgres_volume:/var/lib/postgresql/data
        ports:
            - ${IP}:${POSTGRES_PORT}:5432
    flask:
        build:
            context: ./data/flask
            dockerfile: flask.Dockerfile
        command: gunicorn -w 4 --bind 0.0.0.0:5000 app:app
        volumes:
            - ./data/flask/flask_app_to_deploy:/flask_app_to_deploy
        # ports:
        #     - ${IP}:5000:5000
        depends_on:
            - mysql
volumes:
    mysql_volume:
    postgres_volume:
